# Generated by Django 2.2.19 on 2023-08-27 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название экспоната')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('rating', models.IntegerField(verbose_name='Рейтинг')),
                ('author', models.CharField(max_length=50, verbose_name='Художник')),
                ('question_for_reflection', models.TextField(verbose_name='Вопрос для рефлексии')),
                ('answer_for_reflection', models.TextField(verbose_name='Ответ для рефлексии')),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Экспонат',
                'verbose_name_plural': 'Экспонаты',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название маршрута')),
                ('description', models.TextField(verbose_name='Описание маршрута')),
                ('lyrics', models.TextField(default='', verbose_name='Лирическое описание')),
                ('route_map', models.ImageField(blank=True, help_text='Добавьте карту маршрута', upload_to='excursion/router_map/', verbose_name='Карта маршрута')),
                ('cover', models.ImageField(blank=True, help_text='Добавьте обложку маршрута', upload_to='excursion/cover/', verbose_name='Обложка маршрута')),
                ('rating', models.IntegerField(default=0, verbose_name='Рейтинг')),
                ('where_start', models.TextField(verbose_name='Как пройти к старту')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
            },
        ),
        migrations.CreateModel(
            name='VideoExhibit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('video', models.FileField(upload_to='videos/')),
                ('exhibit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_exhibit', to='excursion.Exhibit')),
            ],
        ),
        migrations.CreateModel(
            name='ReflectionExhibit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20, verbose_name='Комментатор')),
                ('text', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('contact', models.CharField(max_length=50)),
                ('exhibit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflection_exhibit', to='excursion.Exhibit', verbose_name='Рефлексия на экспонат')),
            ],
            options={
                'verbose_name': 'Рефлексия на экспонат',
                'verbose_name_plural': 'Рефлексия  на экспонаты',
            },
        ),
        migrations.CreateModel(
            name='PhotoExhibit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('photo', models.ImageField(blank=True, help_text='Добавьте картинку экспоната', upload_to='excursion/exhibit/', verbose_name='Фотографии экспонатов')),
                ('exhibit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_exhibit', to='excursion.Exhibit')),
            ],
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traveler', models.PositiveIntegerField()),
                ('now_exhibit', models.PositiveIntegerField()),
                ('route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='excursion.Route')),
            ],
        ),
        migrations.AddField(
            model_name='exhibit',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exhibit', to='excursion.Route', verbose_name='Маршрут'),
        ),
        migrations.CreateModel(
            name='DescriptionExhibit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('exhibit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description_exhibit', to='excursion.Exhibit')),
            ],
        ),
        migrations.CreateModel(
            name='AudioExhibit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('audio', models.FileField(upload_to='audios/')),
                ('exhibit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_exhibit', to='excursion.Exhibit')),
            ],
        ),
    ]
