# Generated by Django 2.2.19 on 2023-08-13 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('contact', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('route_map', models.ImageField(blank=True, help_text='Добавьте карту маршрута', upload_to='excursion/router_map/', verbose_name='Карта маршрута')),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, help_text='Добавьте картинку экспоната', upload_to='excursion/exhibit/', verbose_name='Картинка')),
                ('address', models.CharField(max_length=200)),
                ('rating', models.IntegerField()),
                ('author', models.CharField(max_length=50)),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exhibit', to='excursion.Route', verbose_name='Экспонат')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewOnRoute',
            fields=[
                ('reviews_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='excursion.Reviews')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_on_route', to='excursion.Route', verbose_name='Комментируемый маршрут')),
            ],
            bases=('excursion.reviews',),
        ),
        migrations.CreateModel(
            name='ReviewOnExhibit',
            fields=[
                ('reviews_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='excursion.Reviews')),
                ('exhibit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_on_exhibit', to='excursion.Exhibit', verbose_name='Комментируемый экспонат')),
            ],
            bases=('excursion.reviews',),
        ),
    ]
