# Generated by Django 2.2.19 on 2023-08-19 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(unique=True, verbose_name='Внешний ID пользователя')),
                ('name', models.TextField(verbose_name='Имя пользователя')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20, verbose_name='Комментатор')),
                ('text', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('contact', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название маршрута')),
                ('description', models.TextField(verbose_name='Описание экспоната')),
                ('route_map', models.ImageField(blank=True, help_text='Добавьте карту маршрута', upload_to='excursion/router_map/', verbose_name='Карта маршрута')),
                ('rating', models.IntegerField(verbose_name='Рейтинг')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время получения')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='excursion.Profile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traveler', models.PositiveIntegerField()),
                ('now_exhibit', models.PositiveIntegerField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excursion.Route')),
            ],
        ),
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название экспоната')),
                ('description', models.TextField(verbose_name='Описание экспоната')),
                ('image', models.ImageField(blank=True, help_text='Добавьте картинку экспоната', upload_to='excursion/exhibit/', verbose_name='Картинка')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('rating', models.IntegerField(verbose_name='Рейтинг')),
                ('author', models.CharField(max_length=50, verbose_name='Художник')),
                ('order', models.PositiveIntegerField()),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exhibit', to='excursion.Route', verbose_name='Маршрут')),
            ],
            options={
                'verbose_name': 'Экспонат',
                'verbose_name_plural': 'Экспонаты',
            },
        ),
        migrations.CreateModel(
            name='ReviewOnRoute',
            fields=[
                ('reviews_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='excursion.Reviews')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_on_route', to='excursion.Route', verbose_name='Комментируемый маршрут')),
            ],
            options={
                'verbose_name': 'Комментарий на маршрут',
                'verbose_name_plural': 'Комментарии на маршруты',
            },
            bases=('excursion.reviews',),
        ),
        migrations.CreateModel(
            name='ReviewOnExhibit',
            fields=[
                ('reviews_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='excursion.Reviews')),
                ('exhibit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_on_exhibit', to='excursion.Exhibit', verbose_name='Комментируемый экспонат')),
            ],
            options={
                'verbose_name': 'Комментарий на экспонат',
                'verbose_name_plural': 'Комментарии на экспонаты',
            },
            bases=('excursion.reviews',),
        ),
    ]
