# Generated by Django 2.2.19 on 2023-08-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoexhibit',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Рейтинг'),
        ),
    ]
