# Generated by Django 2.2.19 on 2023-08-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursion', '0003_auto_20230829_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibit',
            name='where_start',
            field=models.TextField(blank=True, null=True, verbose_name='Как пройти к экспонату'),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='answer_for_reflection',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ для рефлексии'),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='question_for_reflection',
            field=models.TextField(blank=True, null=True, verbose_name='Вопрос для рефлексии'),
        ),
    ]
