# Generated by Django 2.2.19 on 2023-08-29 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excursion', '0004_auto_20230830_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibit',
            name='rating',
        ),
    ]
