# Generated by Django 2.2.19 on 2023-08-30 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excursion', '0005_remove_exhibit_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='rating',
        ),
    ]
