# Generated by Django 2.2.19 on 2023-08-30 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursion', '0007_remove_exhibit_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibit',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
