# Generated by Django 2.2.19 on 2023-08-30 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursion', '0008_exhibit_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibit',
            name='order',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
    ]
