# Generated by Django 2.2.19 on 2023-08-30 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursion', '0009_auto_20230830_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibit',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
