# Generated by Django 2.2.19 on 2023-08-30 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursion', '0010_auto_20230830_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibit',
            name='order',
            field=models.PositiveIntegerField(auto_created=0),
        ),
    ]
