# Generated by Django 2.2.19 on 2023-08-31 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursion', '0012_auto_20230830_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='question_end',
            field=models.TextField(blank=True, null=True, verbose_name='Вопрос в конце маршрута'),
        ),
        migrations.AddField(
            model_name='route',
            name='show',
            field=models.BooleanField(default=True, verbose_name='Показывать маршрут?'),
        ),
    ]
