# Generated by Django 2.2.19 on 2023-08-31 11:10

from django.db import migrations, models
import excursion.validators


class Migration(migrations.Migration):

    dependencies = [
        ('excursion', '0015_auto_20230831_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoexhibit',
            name='photo',
            field=models.ImageField(blank=True, help_text='Добавьте картинку экспоната', upload_to='excursion/exhibit/', validators=[excursion.validators.file_size_validator, excursion.validators.linear_image_dimensions_validator, excursion.validators.aspect_ratio_validator], verbose_name='Фотографии экспонатов'),
        ),
        migrations.AlterField(
            model_name='route',
            name='cover',
            field=models.ImageField(blank=True, help_text='Добавьте обложку маршрута', upload_to='excursion/cover/', validators=[excursion.validators.file_size_validator, excursion.validators.linear_image_dimensions_validator, excursion.validators.aspect_ratio_validator], verbose_name='Обложка маршрута'),
        ),
        migrations.AlterField(
            model_name='route',
            name='route_map',
            field=models.ImageField(blank=True, help_text='Добавьте карту маршрута', upload_to='excursion/router_map/', validators=[excursion.validators.file_size_validator, excursion.validators.linear_image_dimensions_validator, excursion.validators.aspect_ratio_validator], verbose_name='Карта маршрута'),
        ),
    ]
