# Generated by Django 2.2.19 on 2023-08-31 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excursion', '0016_auto_20230831_1110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journey',
            options={'verbose_name': 'Начатое путешествие', 'verbose_name_plural': 'Начатые путешествия'},
        ),
    ]
