# Generated by Django 2.2.19 on 2023-08-31 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excursion', '0018_auto_20230831_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioexhibit',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание аудио'),
        ),
        migrations.AlterField(
            model_name='descriptionexhibit',
            name='text',
            field=models.TextField(help_text='каждая область - это отдельное сообщение которые будут идти с задержкой пропорционально длине текста, ', verbose_name='Текст сообщения'),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='при добавление нового экспоната ему присваивается последний номер, при редактирование его можно будет поменять', verbose_name='порядок в маршруте'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='now_exhibit',
            field=models.PositiveIntegerField(verbose_name='Номер текущего экспоната'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='excursion.Route', verbose_name='Маршрут'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='traveler',
            field=models.PositiveIntegerField(verbose_name='Путешественник'),
        ),
        migrations.AlterField(
            model_name='photoexhibit',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание фотографии'),
        ),
        migrations.AlterField(
            model_name='videoexhibit',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание видео'),
        ),
    ]
