# Generated by Django 2.2.19 on 2023-09-01 16:05

from django.db import migrations, models
import excursion.validators


class Migration(migrations.Migration):

    dependencies = [
        ('excursion', '0019_auto_20230831_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='traveler',
            field=models.BigIntegerField(verbose_name='Путешественник'),
        ),
        migrations.AlterField(
            model_name='photoexhibit',
            name='photo',
            field=models.ImageField(blank=True, help_text='Добавьте картинку экспоната', upload_to='exhibit/', validators=[excursion.validators.file_size_validator], verbose_name='Фотографии экспонатов'),
        ),
        migrations.AlterField(
            model_name='route',
            name='cover',
            field=models.ImageField(blank=True, help_text='Добавьте обложку маршрута', upload_to='cover/', validators=[excursion.validators.file_size_validator], verbose_name='Обложка маршрута'),
        ),
        migrations.AlterField(
            model_name='route',
            name='route_map',
            field=models.ImageField(blank=True, help_text='Добавьте карту маршрута', upload_to='route_map/', validators=[excursion.validators.file_size_validator], verbose_name='Карта маршрута'),
        ),
    ]
