# Generated by Django 2.2.19 on 2023-09-04 06:40

from django.db import migrations, models
import excursion.validators


class Migration(migrations.Migration):

    dependencies = [
        ('excursion', '0021_auto_20230904_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptionexhibit',
            name='text',
            field=models.TextField(help_text=('каждая область - это отдельное сообщение которые будут идти с задержкой пропорционально длине текста.Для текста предусмотрено форматирование, заключите текст в пару тегов для того, чтобы текст стал:<u>подчеркнутый текст</u> подчеркнутый<del>зачеркнуты текст</del>', '<em>курсив</em>', '<i>курсив</i>', '<strong>жирный</strong>', '<b>жирный</b>', '<a href ="ссылка"> текст </a>'), validators=[excursion.validators.html_validator], verbose_name='Текст сообщения'),
        ),
    ]
