# Generated by Django 2.2.19 on 2023-08-13 22:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('excursion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('start_time_route', models.DateTimeField()),
                ('end_time_route', models.DateTimeField(blank=True, null=True)),
                ('exhibit_comment', models.BooleanField(default=False)),
                ('route_review', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Feedback пользователя',
                'verbose_name_plural': 'Feedback пользователей',
            },
        ),
        migrations.CreateModel(
            name='RouteReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('rating_route', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excursion.Route')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistic.UserFeedback')),
            ],
        ),
        migrations.CreateModel(
            name='ExhibitComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('rating_exhibit', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('exhibit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excursion.Exhibit')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistic.UserFeedback')),
            ],
        ),
    ]
