# Generated by Django 2.2.19 on 2023-08-27 18:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('excursion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(blank=True, max_length=150)),
                ('start_time_route', models.DateTimeField(auto_now_add=True)),
                ('end_time_route', models.DateTimeField(blank=True, null=True)),
                ('route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='excursion.Route')),
            ],
            options={
                'verbose_name': 'Feedback пользователя',
                'verbose_name_plural': 'Feedback пользователей',
            },
        ),
        migrations.CreateModel(
            name='RouteReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('rating_route', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excursion.Route')),
                ('user_feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='google_api.UserFeedback')),
            ],
        ),
        migrations.CreateModel(
            name='ExhibitComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('rating_exhibit', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('exhibit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excursion.Exhibit')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excursion.Route')),
                ('user_feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='google_api.UserFeedback')),
            ],
        ),
    ]
